#!/usr/bin/env python3
"""Bundle the site into one self-contained .html for sharing by email.

The repo keeps images as separate files so they cache independently when
deployed. That means index.html cannot be opened on its own. This inlines every
local asset as a data URI so the result is a single file anyone can open with no
server, no repo, and no internet beyond fonts.

Not a deploy artifact — deploy the repo as-is. This is only for handing a
reviewer something that works when double-clicked.
"""
import base64, mimetypes, pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / 'index.html').read_text(encoding='utf-8')
out_path = root / 'dist' / 'uptown-ortho-preview.html'
out_path.parent.mkdir(exist_ok=True)

inlined, missing, total = {}, [], 0

def data_uri(rel):
    global total
    p = (root / rel).resolve()
    if not p.is_file():
        missing.append(rel); return None
    if rel not in inlined:
        mime = mimetypes.guess_type(p.name)[0] or 'application/octet-stream'
        raw = p.read_bytes(); total += len(raw)
        inlined[rel] = f"data:{mime};base64,{base64.b64encode(raw).decode()}"
    return inlined[rel]

# url('assets/...') in inline styles and CSS
def css_repl(m):
    uri = data_uri(m.group(2))
    return m.group(0) if uri is None else f"url({m.group(1)}{uri}{m.group(1)})"
src = re.sub(r"url\((['\"]?)(assets/[^'\")]+)\1\)", css_repl, src)

# src="assets/..." and href="assets/..." on img / link
def attr_repl(m):
    uri = data_uri(m.group(2))
    return m.group(0) if uri is None else f'{m.group(1)}="{uri}"'
src = re.sub(r'\b(src|href)="(assets/[^"]+)"', attr_repl, src)

banner = ("<!-- Portable single-file build. Generated by scripts/build-portable.py -\n"
          "     do not edit directly; edit index.html and regenerate. -->\n")
src = src.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + banner, 1)
out_path.write_text(src, encoding='utf-8')

print(f"inlined {len(inlined)} assets ({total/1024:.0f} KB raw)")
for r in sorted(inlined): print(f"   {r}")
if missing:
    print("MISSING:", *missing, sep="\n   "); sys.exit(1)
print(f"\nwrote {out_path.relative_to(root)}  ({out_path.stat().st_size/1024:.0f} KB)")
left = re.findall(r'["\'(](assets/[^"\')]+)', src)
print("unresolved local refs:", left or "none")
